### ISSUE TITLE
Adding Valid API Keys - Presents validation errors

### ISSUE THREAD

**Issue by IISlapDashII** [alhazmy13/streamdeck-sensibo#1]
Entering valid API key's presented with key not valid

![image](https://user-images.githubusercontent.com/29777193/203223235-5ba0f20a-975d-4866-8550-b5540a07facc.png)

![image](https://user-images.githubusercontent.com/29777193/203223371-c070132d-4d8b-44f1-aaad-6f7c9cab26ee.png)

Generating subsequent new/additional keys presents the same issue? 

![image](https://user-images.githubusercontent.com/29777193/203223544-645ab915-939a-4d78-aa3e-ec8a30b9af0e.png)

![image](https://user-images.githubusercontent.com/29777193/203224024-1b256328-bf65-4c61-92d0-88d677242333.png)

**Comment by alhazmy13** [comment]
Hi @IISlapDashII 

Thank you for using and testing the plugin; for your issue, I have three reasons on my mind right now for this issue:

1.  Are you using the latest version of Stream deck version 6? If yes, then this is why you have this issue. With the latest version, most Javascript plugins that use API calls are stopped working anymore. For more details: (https://www.reddit.com/r/StreamDeckSDK/comments/yxm1zb/comment/iwqtxu0/?utm_source=share&utm_medium=web2x&context=3) 
Luckily Elgato released a beta version to fix this issue; can you please download the beta version and check again if this fixes your issue or not?
Download URL:  https://www.reddit.com/r/StreamDeckSDK/comments/yxm1zb/comment/ix8oc6a/?utm_source=share&utm_medium=web2x&context=3

2. Is there any spaces at the end of the API key input field? If yes, please remove any spaces at the start or the end of the field.
3. It could be a bug. Currently, I'm working on a new release that enhances all of the plugin actions, ill review this page before I publish the new version.

**Comment by IISlapDashII** [comment]
1. Thanks for the quick reply. I can confirm am using the latest version of Stream Deck Version 6.0.0.17703. 
Installing Beta version here: https://edge.elgato.com/egc/windows/sd/Stream_Deck_6.0.1.17713.msi 
Resolved the problem. 👍🏽 

![image](https://user-images.githubusercontent.com/29777193/203250353-a40c1a4b-88ad-4101-8e43-5459a8b7bd38.png)

2. N/A 
3. N/A

It does seem to be related to the JavaScript & Cors policy issue per reddit link provided. Thanks again!
