### ISSUE TITLE
API key not accepted

### ISSUE THREAD

**Issue by Geeekie** [alhazmy13/streamdeck-sensibo#3]
Hey there, its throwing me an error when trying to input my API Key 
![image](https://user-images.githubusercontent.com/7633313/204340813-8b126441-4476-42a4-8fad-69552e4e9a76.png)
Have confirmed that the API keys are valid by testing in my Node Red and Home assistant instances. any ideas?

**Comment by alhazmy13** [comment]
Hi @Geekie2014 

Can you please check this https://github.com/alhazmy13/streamdeck-sensibo/issues/1#issuecomment-1323205258 and confirm if it fixes your issue or not?

Thanks

**Comment by Geeekie** [comment]
This fixed it, thanks!
